name: Trigger Deployment

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: デプロイ
        required: true

jobs:
  verify-actor:
    runs-on: ubuntu-latest
    outputs:
      actor: ${{ steps.echo.outputs.actor }}
    steps:
      - name: echo actor
        id: echo
        run: |
          echo "::set-output name=actor::${{ github.actor }}"
  

  trigger_deploy:
    runs-on: ubuntu-latest
    needs: [verify-actor]
    if: ${{ needs.verify-actor.outputs.actor }} != "shmokmt"
    steps:
      - uses: actions/checkout@v2

      - name: Create and push branch.
        env:
          DEPLOY: ${{ github.event.inputs.deploy }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${DEPLOY}
          git push --set-upstream --force origin ${DEPLOY}
