name: Trigger Deployment

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        description: dryrun
        default: true
        required: true
      target:
        description: target
        type: choice
        required: true
        options:
          - A
          - B
          - C

jobs:
  print-input-value:
    runs-on: ubuntu-latest
    steps:
      - name: print
        if: ${{ github.event.input.dryrun }} == "true"
        run: |
          echo "target: ${{ github.event.inputs.target }}"
          echo "dryrun: ${{ github.event.inputs.dryrun }}"
  



