name: PR
on: [pull_request, push]

jobs:
  act:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sleep 10
      - name: setup-tfcmt
        uses: shmokmt/actions-setup-tfcmt@v1
        with:
          version: v2.0.2
