name: Push
on:
  push:
    branches:
      - push
      - push2
  

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cat
        run: echo '${{ github.ref#refs/heads/ }}'
