name: Push
on:
  push:
    branches:
      - push
      - push2
      - artifact
  

jobs:
  matrix:
    name: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallelism: [5]
        node_id: [0, 1, 2, 3, 4]
    steps:
      - name: mkdir
        run: mkdir -p tmp

      - name: echo
        run: echo ${{ matrix.node_id }} > ./tmp/${{ matrix.node_id }}

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: ./tmp/${{ matrix.node_id }}
  
  artifact:
    name: artifact
    needs: [matrix]
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: result
          path: ~
      - name: ls
        run: ls -alh
        



